name: CI (Python/ML)
on:
  push:
    branches: [ main, develop ]
  pull_request:
permissions:
  contents: read
  packages: write
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          pip install ruff
          ruff check .
      - name: Build serving image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/model-serving:sha-${{ github.sha }}
          docker build -f serving/Dockerfile -t $IMAGE .
      - name: Login GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/model-serving:sha-${{ github.sha }}
          docker push $IMAGE